#!/usr/bin/env python3
"""Writes the word tables of Specs/assistant_rules.t27 from the readable lists below."""
import pathlib, re

# Tables (must match AS_TABLE_* in the spec). Row code: a section, a verdict or a hint id.
SECTION, VERDICT, LOCAL_HOST, NON_CHAT, TOOL_FAMILY, YES_WORD, HTTP_HINT = range(7)
# Sections as WorkspaceSection order in Swift: diskMap, appUninstaller, orphanedAppData, duplicateFinder, cacheExplorer
DISK_MAP, UNINSTALLER, LEFTOVERS, DUPLICATES, CACHES = range(5)
# Verdict codes as CV_* in Specs/cache_verdict.t27
SAFE, OPTIONAL, QUIT_FIRST, USE_TOOL, KEEP = range(5)

sections = [("disk_map", DISK_MAP), ("diskmap", DISK_MAP), ("map", DISK_MAP), ("caches", CACHES), ("cache", CACHES),
            ("app_uninstaller", UNINSTALLER), ("uninstaller", UNINSTALLER), ("apps", UNINSTALLER),
            ("leftovers", LEFTOVERS), ("possible_leftovers", LEFTOVERS), ("duplicates", DUPLICATES), ("duplicate_files", DUPLICATES)]
verdicts = [("safe", SAFE), ("optional", OPTIONAL), ("in_use", QUIT_FIRST), ("quitfirst", QUIT_FIRST), ("quit_first", QUIT_FIRST),
            ("keep", KEEP), ("tool", USE_TOOL), ("use_tool", USE_TOOL)]
local_hosts = ["localhost", "127.0.0.1", "::1"]
non_chat = ["embed", "rerank", "reward", "guard", "safety", "content-safety", "topic-control", "nemoretriever",
            "retriever", "parse", "clip", "vila", "neva", "deplot", "kosmos", "fuyu", "riva", "detector",
            "calibration", "whisper", "tts", "diffusion", "cosmos", "paligemma", "starcoder", "codegemma"]
tool_families = ["kimi-k", "glm-4.5", "glm-4.6", "glm-5", "deepseek-v3", "deepseek-v4", "gpt-oss", "gpt-4", "gpt-5",
                 "nemotron-3-super", "nemotron-3-ultra", "nemotron-ultra", "mistral-large", "qwen3", "qwen2.5",
                 "llama-3.1-70b", "llama-3.3", "llama-4", "gemma-4", "claude", "gemini"]
yes_words = ["true", "yes", "1"]
# HTTP status (as text) -> hint shown after an API error
http_hints = [("401", " Check the API key."), ("403", " Check the API key."),
              ("404", " The address is wrong or this provider has no model with that name — pick one from the model list."),
              ("429", " The provider's rate limit or balance ran out.")]

rows = []
rows += [(SECTION, n, "", c) for n, c in sections]
rows += [(VERDICT, n, "", c) for n, c in verdicts]
rows += [(LOCAL_HOST, n, "", 0) for n in local_hosts]
rows += [(NON_CHAT, n, "", 0) for n in non_chat]
rows += [(TOOL_FAMILY, n, "", 0) for n in tool_families]
rows += [(YES_WORD, n, "", 0) for n in yes_words]
rows += [(HTTP_HINT, n, h, int(n)) for n, h in http_hints]

text = bytearray(); f0o=[]; f0l=[]; f1o=[]; f1l=[]
for _, a, b, _ in rows:
    f0o.append(len(text)); f0l.append(len(a.encode())); text += a.encode()
    f1o.append(len(text)); f1l.append(len(b.encode())); text += b.encode()
def arr(name, typ, values): return f"pub const {name} : [{len(values)}]{typ} = [{', '.join(map(str, values))}];"
lines = ["; >>> generated by Specs/tables/assistant_tables.py -- edit the lists there, not here",
         f"pub const AS_ROWS : u32 = {len(rows)};",
         arr("AS_ROW_TABLE", "u32", [r[0] for r in rows]), arr("AS_ROW_CODE", "u32", [r[3] for r in rows]),
         arr("AS_ROW_F0_OFFSET", "u32", f0o), arr("AS_ROW_F0_LENGTH", "u32", f0l),
         arr("AS_ROW_F1_OFFSET", "u32", f1o), arr("AS_ROW_F1_LENGTH", "u32", f1l),
         arr("AS_TEXT", "u8", list(text)), "; <<< generated"]
spec = pathlib.Path(__file__).resolve().parents[1] / "assistant_rules.t27"
source = spec.read_text()
source, n = re.subn(r"; >>> generated by Specs/tables/assistant_tables\.py.*?; <<< generated", lambda m: "\n".join(lines), source, flags=re.S)
assert n == 1
spec.write_text(source)
print(f"assistant tables: {len(rows)} rows, {len(text)} bytes")
