// Model lists captured from the NVIDIA and OpenRouter /models endpoints on 2026-10-07, for offline tests.
enum CapturedModelIDs {
    static let nvidia: [String] = [
        "01-ai/yi-large",
        "adept/fuyu-8b",
        "ai21labs/jamba-1.5-large-instruct",
        "aisingapore/sea-lion-7b-instruct",
        "bigcode/starcoder2-15b",
        "databricks/dbrx-instruct",
        "deepseek-ai/deepseek-coder-6.7b-instruct",
        "deepseek-ai/deepseek-v4.1-flash",
        "google/codegemma-1.1-7b",
        "google/codegemma-7b",
        "google/deplot",
        "google/diffusiongemma-26b-a4b-it",
        "google/gemma-2b",
        "google/gemma-3-12b-it",
        "google/gemma-3-4b-it",
        "google/gemma-4-31b-it",
        "google/recurrentgemma-2b",
        "ibm/granite-3.0-3b-a800m-instruct",
        "ibm/granite-3.0-8b-instruct",
        "ibm/granite-34b-code-instruct",
        "ibm/granite-8b-code-instruct",
        "meta/codellama-70b",
        "meta/llama-3.2-11b-vision-instruct",
        "meta/llama-3.2-90b-vision-instruct",
        "meta/llama-guard-4-12b",
        "meta/llama2-70b",
        "meta/muse-glimmer-30b",
        "microsoft/kosmos-2",
        "microsoft/phi-3-vision-128k-instruct",
        "microsoft/phi-3.5-moe-instruct",
        "mistralai/codestral-22b-instruct-v0.1",
        "mistralai/mistral-7b-instruct-v0.3",
        "mistralai/mistral-large",
        "mistralai/mistral-large-2-instruct",
        "mistralai/mixtral-8x22b-v0.1",
        "moonshotai/kimi-k2.6",
        "moonshotai/kimi-k3",
        "nv-mistralai/mistral-nemo-12b-instruct",
        "nvidia/ai-synthetic-video-detector",
        "nvidia/cosmos-reason2-8b",
        "nvidia/embed-qa-4",
        "nvidia/ising-calibration-1.5-31b",
        "nvidia/llama-3.1-nemoguard-8b-content-safety",
        "nvidia/llama-3.1-nemoguard-8b-topic-control",
        "nvidia/llama-3.1-nemotron-51b-instruct",
        "nvidia/llama-3.1-nemotron-70b-instruct",
        "nvidia/llama-3.1-nemotron-safety-guard-8b-v3",
        "nvidia/llama-3.1-nemotron-ultra-253b-v1",
        "nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1",
        "nvidia/llama-3.2-nv-embedqa-1b-v1",
        "nvidia/llama-nemotron-embed-vl-1b-v2",
        "nvidia/llama3-chatqa-1.5-70b",
        "nvidia/mistral-nemo-minitron-8b-8k-instruct",
        "nvidia/nemotron-3-embed-1b",
        "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
        "nvidia/nemotron-3-super-120b-a12b",
        "nvidia/nemotron-3-ultra-550b-a55b",
        "nvidia/nemotron-3.5-content-safety",
        "nvidia/nemotron-3.5-lightning-30b-a3b",
        "nvidia/nemotron-4-340b-instruct",
        "nvidia/nemotron-4-340b-reward",
        "nvidia/nemotron-nano-3-30b-a3b",
        "nvidia/nemotron-parse",
        "nvidia/nemotron-parse-2.0",
        "nvidia/neva-22b",
        "nvidia/nv-embedqa-mistral-7b-v2",
        "nvidia/nvclip",
        "nvidia/riva-translate-4b-instruct",
        "nvidia/riva-translate-4b-instruct-v2",
        "nvidia/vila",
        "openai/gpt-oss-20b",
        "poolside/laguna-xs-2.1",
        "snowflake/arctic-embed-l",
        "writer/palmyra-creative-122b",
        "writer/palmyra-fin-70b-32k",
        "writer/palmyra-med-70b",
        "writer/palmyra-med-70b-32k",
        "z-ai/glm-5.3",
        "z-ai/glm-5.3-flash",
        "zyphra/zamba2-7b-instruct",
    ]
    static let openRouter: [(String, Bool?)] = [
        ("google/gemini-nano-banana-2.1", true),
        ("mistralai/mistral-large-4-0", true),
        ("inclusionai/ling-3.1-flash", true),
        ("apodex/apodex-1.1-mini:free", true),
        ("unbiased/pareto-26.10-preview", true),
        ("openai/gpt-6.1-sol-pro", true),
        ("openai/gpt-6.1-sol", true),
        ("anthropic/claude-sonnet-5.5", true),
        ("anthropic/claude-sonnet-5.5:batch", true),
        ("typesafe/jev-router", true),
        ("perceptron/perceptron-mk1.5", true),
        ("fireworks/ember-1", true),
        ("z-ai/glm-5.3-prime", true),
        ("qwen/qwen3.8-max-prime", true),
        ("aion-labs/aion-3.5-mini", true),
        ("aion-labs/aion-3.5", true),
        ("upstage/solar-mini4", true),
        ("cohere/command-a-plus", true),
        ("openai/gpt-6-luna-pro", true),
        ("openai/gpt-6-luna-pro:batch", true),
        ("openai/gpt-6-luna", true),
        ("openai/gpt-6-luna:batch", true),
        ("openai/gpt-6-sol-pro", true),
        ("openai/gpt-6-sol-pro:batch", true),
        ("openai/gpt-6-sol", true),
        ("openai/gpt-6-sol:batch", true),
        ("anthropic/claude-opus-5.5", true),
        ("anthropic/claude-opus-5.5:batch", true),
        ("nvidia/switchyard", false),
        ("xiaomi/mimo-v2.6-pro-ultraspeed", true),
        ("xiaomi/mimo-v2.6-flash", true),
        ("xiaomi/mimo-v2.6-pro", true),
        ("x-ai/grok-4.7", true),
        ("qwen/qwen3.8-omni-flash", true),
        ("prism-ml/ternary-bonsai-2-27b", true),
        ("z-ai/glm-5.3-flashx", true),
        ("unbiased/pareto", true),
        ("~deepseek/deepseek-pro-latest", true),
        ("~deepseek/deepseek-flash-latest", true),
        ("inference-net/schematron-v2-turbo", false),
        ("inference-net/schematron-v2-small", false),
        ("~openai/gpt-astra-latest", true),
        ("~openai/gpt-sol-latest", true),
        ("~openai/gpt-terra-latest", true),
        ("~openai/gpt-luna-latest", true),
        ("sakana/fugu-ultra-v2", true),
        ("sakana/fugu-max", true),
        ("inclusionai/ling-3.0-flash-vl", true),
        ("deepseek/deepseek-v4.1-flash", true),
        ("deepseek/deepseek-v4.1-flash:batch", true),
        ("inception/mercury-2.5", true),
        ("nex-agi/nex-n2.5-mini", false),
        ("nex-agi/nex-n2.5-pro", true),
        ("openai/gpt-6-astra", true),
        ("openai/gpt-6-astra:batch", true),
        ("openai/gpt-6-astra-pro", true),
        ("openai/gpt-6-astra-pro:batch", true),
        ("inclusionai/ling-3.0-flash-sante:free", true),
        ("qwen/qwen3.8-max-0902", true),
        ("meta/muse-spark-1.3-contributor", true),
        ("meta/muse-spark-1.3", true),
        ("google/gemini-3.8-flash", true),
        ("google/gemini-3.8-flash:batch", true),
        ("anthropic/claude-fable-5.1", true),
        ("anthropic/claude-fable-5.1:batch", true),
        ("ibm-granite/granite-4.2-8b", true),
        ("tencent/hy4-preview", true),
        ("inclusionai/ling-3.0-flash-fin", true),
        ("~z-ai/glm-flash-latest", true),
        ("qwen/qwen3.8-flash", true),
        ("z-ai/glm-5.3-flash", true),
        ("z-ai/glm-5.3-flash:batch", true),
        ("meta/muse-spark-1.2-contributor", true),
        ("deepseek/deepseek-v4-flash-vision-exp", true),
        ("tencent/hy-mt2-1.8b", false),
        ("tencent/hy-mt2-30b-a3b", false),
        ("~z-ai/glm-latest", true),
        ("tencent/hy-mt2-7b", false),
        ("z-ai/glm-5.3", true),
        ("z-ai/glm-5.3:batch", true),
        ("qwen/qwen3.8-27b", true),
        ("dots-studio/dots-3-note-preview:free", true),
        ("google/gemini-3.7-flash", true),
        ("google/gemini-3.7-flash:batch", true),
        ("bytedance-seed/seed-2-1-turbo", true),
        ("qwen/qwen3.8-2.4t-a95b", true),
        ("bytedance-seed/seed-2.0-code", true),
        ("deepseek/deepseek-v4-pro-0813", true),
        ("x-ai/grok-4.6", true),
        ("liquid/lfm-2.5-2.6b:free", true),
        ("nvidia/nemotron-3.5-lightning", true),
        ("nvidia/nemotron-3.5-lightning:free", true),
        ("sakana/sakana-namazu", true),
        ("upstage/solar-pro4", true),
        ("meta/muse-glimmer-30b", true),
        ("meta/muse-spark-1.2", true),
        ("~deepseek/deepseek-v4-flash-latest", true),
        ("deepseek/deepseek-v4-flash-0731", true),
        ("thinkingmachines/inkling-small", true),
        ("thinkingmachines/inkling-small:free", true),
        ("qwen/qwen3.7-flash", true),
        ("anthropic/claude-opus-5", true),
        ("anthropic/claude-opus-5:batch", true),
        ("inclusionai/ling-3.0-flash", true),
        ("poolside/laguna-s-2.1", true),
        ("poolside/laguna-s-2.1:free", true),
        ("google/gemini-3.6-flash", true),
        ("google/gemini-3.6-flash:batch", true),
        ("google/gemini-3.5-flash-lite", true),
        ("google/gemini-3.5-flash-lite:batch", true),
        ("meituan/longcat-2.0", true),
        ("thinkingmachines/inkling", true),
        ("thinkingmachines/inkling:free", true),
        ("openrouter/auto-beta", true),
        ("moonshotai/kimi-k3", true),
        ("moonshotai/kimi-k3:batch", true),
        ("meta/muse-spark-1.1", true),
        ("openai/gpt-5.6-luna-pro", true),
        ("openai/gpt-5.6-luna-pro:batch", true),
        ("openai/gpt-5.6-luna", true),
        ("openai/gpt-5.6-luna:batch", true),
        ("openai/gpt-5.6-terra-pro", true),
        ("openai/gpt-5.6-terra-pro:batch", true),
        ("openai/gpt-5.6-terra", true),
        ("openai/gpt-5.6-terra:batch", true),
        ("openai/gpt-5.6-sol-pro", true),
        ("openai/gpt-5.6-sol-pro:batch", true),
        ("openai/gpt-5.6-sol", true),
        ("openai/gpt-5.6-sol:batch", true),
        ("x-ai/grok-4.5", true),
        ("~x-ai/grok-latest", true),
        ("aion-labs/aion-3.0-mini", true),
        ("aion-labs/aion-3.0", true),
        ("tencent/hy3", true),
        ("poolside/laguna-xs-2.1", true),
        ("poolside/laguna-xs-2.1:free", true),
        ("anthropic/claude-sonnet-5", true),
        ("anthropic/claude-sonnet-5:batch", true),
        ("google/gemini-3.1-flash-lite-image", false),
        ("sakana/fugu-ultra", true),
        ("google/gemini-3.1-flash-image", false),
        ("google/gemini-3-pro-image", true),
        ("cohere/north-mini-code:free", true),
        ("z-ai/glm-5.2", true),
        ("openrouter/fusion", false),
        ("moonshotai/kimi-k2.7-code", true),
        ("~anthropic/claude-fable-latest", true),
        ("anthropic/claude-fable-5", true),
        ("anthropic/claude-fable-5:batch", true),
        ("nvidia/nemotron-3.5-content-safety", false),
        ("nvidia/nemotron-3.5-content-safety:free", false),
        ("nvidia/nemotron-3-ultra-550b-a55b", true),
        ("nvidia/nemotron-3-ultra-550b-a55b:free", true),
        ("qwen/qwen3.7-plus", true),
        ("minimax/minimax-m3", true),
        ("stepfun/step-3.7-flash", true),
        ("anthropic/claude-opus-4.8", true),
        ("anthropic/claude-opus-4.8:batch", true),
        ("qwen/qwen3.7-max", true),
        ("x-ai/grok-build-0.1", true),
        ("google/gemini-3.5-flash", true),
        ("google/gemini-3.5-flash:batch", true),
        ("perceptron/perceptron-mk1", false),
        ("google/gemini-3.1-flash-lite", true),
        ("google/gemini-3.1-flash-lite:batch", true),
        ("openai/gpt-chat-latest", true),
        ("x-ai/grok-4.3", true),
        ("x-ai/grok-4.3:batch", true),
        ("mistralai/mistral-medium-3-5", true),
        ("mistralai/mistral-medium-3-5:batch", true),
        ("nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", true),
        ("~anthropic/claude-haiku-latest", true),
        ("~openai/gpt-mini-latest", true),
        ("~google/gemini-pro-latest", true),
        ("~moonshotai/kimi-latest", true),
        ("~google/gemini-flash-latest", true),
        ("~anthropic/claude-sonnet-latest", true),
        ("qwen/qwen3.5-plus-20260420", true),
        ("qwen/qwen3.6-flash", true),
        ("qwen/qwen3.6-35b-a3b", true),
        ("qwen/qwen3.6-max-preview", true),
        ("qwen/qwen3.6-27b", true),
        ("openai/gpt-5.5-pro", true),
        ("openai/gpt-5.5-pro:batch", true),
        ("openai/gpt-5.5", true),
        ("openai/gpt-5.5:batch", true),
        ("deepseek/deepseek-v4-pro", true),
        ("deepseek/deepseek-v4-flash", true),
        ("tencent/hy3-preview", true),
        ("xiaomi/mimo-v2.5-pro", true),
        ("xiaomi/mimo-v2.5", true),
        ("openai/gpt-5.4-image-2", false),
        ("~anthropic/claude-opus-latest", true),
        ("openrouter/pareto-code", false),
        ("moonshotai/kimi-k2.6", true),
        ("anthropic/claude-opus-4.7", true),
        ("anthropic/claude-opus-4.7:batch", true),
        ("z-ai/glm-5.1", true),
        ("google/gemma-4-26b-a4b-it", true),
        ("google/gemma-4-26b-a4b-it:free", true),
        ("google/gemma-4-31b-it", true),
        ("google/gemma-4-31b-it:free", true),
        ("qwen/qwen3.6-plus", true),
        ("z-ai/glm-5v-turbo", true),
        ("arcee-ai/trinity-large-thinking", true),
        ("x-ai/grok-4.20-multi-agent", false),
        ("x-ai/grok-4.20", true),
        ("google/lyria-3-pro-preview", false),
        ("google/lyria-3-clip-preview", false),
        ("rekaai/reka-edge", true),
        ("minimax/minimax-m2.7", true),
        ("openai/gpt-5.4-nano", true),
        ("openai/gpt-5.4-nano:batch", true),
        ("openai/gpt-5.4-mini", true),
        ("openai/gpt-5.4-mini:batch", true),
        ("mistralai/mistral-small-2603", true),
        ("mistralai/mistral-small-2603:batch", true),
        ("z-ai/glm-5-turbo", true),
        ("nvidia/nemotron-3-super-120b-a12b", true),
        ("nvidia/nemotron-3-super-120b-a12b:free", true),
        ("bytedance-seed/seed-2.0-lite", true),
        ("qwen/qwen3.5-9b", true),
        ("openai/gpt-5.4-pro", true),
        ("openai/gpt-5.4-pro:batch", true),
        ("openai/gpt-5.4", true),
        ("openai/gpt-5.4:batch", true),
        ("inception/mercury-2", true),
        ("google/gemini-3.1-flash-lite-preview", true),
        ("bytedance-seed/seed-2.0-mini", true),
        ("google/gemini-3.1-flash-image-preview", false),
        ("qwen/qwen3.5-35b-a3b", true),
        ("qwen/qwen3.5-27b", true),
        ("qwen/qwen3.5-122b-a10b", true),
        ("qwen/qwen3.5-flash-02-23", true),
        ("google/gemini-3.1-pro-preview-customtools", true),
        ("openai/gpt-5.3-codex", true),
        ("aion-labs/aion-2.0", true),
        ("google/gemini-3.1-pro-preview", true),
        ("google/gemini-3.1-pro-preview:batch", true),
        ("anthropic/claude-sonnet-4.6", true),
        ("anthropic/claude-sonnet-4.6:batch", true),
        ("qwen/qwen3.5-plus-02-15", true),
        ("qwen/qwen3.5-397b-a17b", true),
        ("minimax/minimax-m2.5", true),
        ("z-ai/glm-5", true),
        ("qwen/qwen3-max-thinking", true),
        ("anthropic/claude-opus-4.6", true),
        ("anthropic/claude-opus-4.6:batch", true),
        ("qwen/qwen3-coder-next", true),
        ("openrouter/free", true),
        ("stepfun/step-3.5-flash", true),
        ("moonshotai/kimi-k2.5", true),
        ("upstage/solar-pro-3", true),
        ("minimax/minimax-m2-her", false),
        ("writer/palmyra-x5", false),
        ("openai/gpt-audio", true),
        ("openai/gpt-audio-mini", true),
        ("z-ai/glm-4.7-flash", true),
        ("openai/gpt-5.2-codex", true),
        ("bytedance-seed/seed-1.6-flash", true),
        ("bytedance-seed/seed-1.6", true),
        ("minimax/minimax-m2.1", true),
        ("z-ai/glm-4.7", true),
        ("google/gemini-3-flash-preview", true),
        ("google/gemini-3-flash-preview:batch", true),
        ("nvidia/nemotron-3-nano-30b-a3b", true),
        ("openai/gpt-5.2-chat", true),
        ("openai/gpt-5.2-pro", true),
        ("openai/gpt-5.2-pro:batch", true),
        ("openai/gpt-5.2", true),
        ("openai/gpt-5.2:batch", true),
        ("mistralai/devstral-2512", true),
        ("relace/relace-search", true),
        ("z-ai/glm-4.6v", true),
        ("openrouter/bodybuilder", false),
        ("openai/gpt-5.1-codex-max", true),
        ("amazon/nova-2-lite-v1", true),
        ("mistralai/ministral-14b-2512", true),
        ("mistralai/ministral-8b-2512", true),
        ("mistralai/ministral-8b-2512:batch", true),
        ("mistralai/ministral-3b-2512", true),
        ("mistralai/mistral-large-2512", true),
        ("mistralai/mistral-large-2512:batch", true),
        ("deepseek/deepseek-v3.2", true),
        ("anthropic/claude-opus-4.5", true),
        ("anthropic/claude-opus-4.5:batch", true),
        ("google/gemini-3-pro-image-preview", false),
        ("openai/gpt-5.1", true),
        ("openai/gpt-5.1:batch", true),
        ("openai/gpt-5.1-codex", true),
        ("openai/gpt-5.1-codex-mini", true),
        ("moonshotai/kimi-k2-thinking", true),
        ("amazon/nova-premier-v1", true),
        ("perplexity/sonar-pro-search", false),
        ("mistralai/voxtral-small-24b-2507", true),
        ("openai/gpt-oss-safeguard-20b", true),
        ("minimax/minimax-m2", true),
        ("qwen/qwen3-vl-32b-instruct", true),
        ("ibm-granite/granite-4.0-h-micro", false),
        ("openai/gpt-5-image-mini", false),
        ("anthropic/claude-haiku-4.5", true),
        ("anthropic/claude-haiku-4.5:batch", true),
        ("qwen/qwen3-vl-8b-thinking", true),
        ("qwen/qwen3-vl-8b-instruct", true),
        ("openai/gpt-5-image", false),
        ("google/gemini-2.5-flash-image", false),
        ("qwen/qwen3-vl-30b-a3b-thinking", true),
        ("qwen/qwen3-vl-30b-a3b-instruct", true),
        ("openai/gpt-5-pro", true),
        ("openai/gpt-5-pro:batch", true),
        ("z-ai/glm-4.6", true),
        ("anthropic/claude-sonnet-4.5", true),
        ("anthropic/claude-sonnet-4.5:batch", true),
        ("deepseek/deepseek-v3.2-exp", true),
        ("thedrummer/cydonia-24b-v4.1", false),
        ("relace/relace-apply-3", false),
        ("qwen/qwen3-vl-235b-a22b-thinking", true),
        ("qwen/qwen3-vl-235b-a22b-instruct", true),
        ("qwen/qwen3-max", true),
        ("qwen/qwen3-coder-plus", true),
        ("deepseek/deepseek-v3.1-terminus", true),
        ("qwen/qwen3-coder-flash", true),
        ("qwen/qwen3-next-80b-a3b-thinking", true),
        ("qwen/qwen3-next-80b-a3b-instruct", true),
        ("qwen/qwen-plus-2025-07-28", true),
        ("moonshotai/kimi-k2-0905", true),
        ("qwen/qwen3-30b-a3b-thinking-2507", true),
        ("nousresearch/hermes-4-405b", false),
        ("deepseek/deepseek-chat-v3.1", true),
        ("mistralai/mistral-medium-3.1", true),
        ("mistralai/mistral-medium-3.1:batch", true),
        ("z-ai/glm-4.5v", true),
        ("openai/gpt-5", true),
        ("openai/gpt-5:batch", true),
        ("openai/gpt-5-mini", true),
        ("openai/gpt-5-mini:batch", true),
        ("openai/gpt-5-nano", true),
        ("openai/gpt-5-nano:batch", true),
        ("openai/gpt-oss-120b", true),
        ("openai/gpt-oss-120b:batch", true),
        ("openai/gpt-oss-20b", true),
        ("openai/gpt-oss-20b:batch", true),
        ("anthropic/claude-opus-4.1", true),
        ("anthropic/claude-opus-4.1:batch", true),
        ("mistralai/codestral-2508", true),
        ("mistralai/codestral-2508:batch", true),
        ("qwen/qwen3-coder-30b-a3b-instruct", true),
        ("qwen/qwen3-30b-a3b-instruct-2507", true),
        ("z-ai/glm-4.5", true),
        ("z-ai/glm-4.5-air", true),
        ("qwen/qwen3-235b-a22b-thinking-2507", true),
        ("qwen/qwen3-coder", true),
        ("bytedance/ui-tars-1.5-7b", false),
        ("google/gemini-2.5-flash-lite", true),
        ("google/gemini-2.5-flash-lite:batch", true),
        ("qwen/qwen3-235b-a22b-2507", true),
        ("moonshotai/kimi-k2", true),
        ("cognitivecomputations/dolphin-mistral-24b-venice-edition", false),
        ("tencent/hunyuan-a13b-instruct", false),
        ("morph/morph-v3-large", false),
        ("morph/morph-v3-fast", false),
        ("baidu/ernie-4.5-vl-424b-a47b", false),
        ("mistralai/mistral-small-3.2-24b-instruct", true),
        ("minimax/minimax-m1", true),
        ("google/gemini-2.5-flash", true),
        ("google/gemini-2.5-flash:batch", true),
        ("google/gemini-2.5-pro", true),
        ("google/gemini-2.5-pro:batch", true),
        ("openai/o3-pro", true),
        ("google/gemini-2.5-pro-preview", true),
        ("deepseek/deepseek-r1-0528", true),
        ("anthropic/claude-sonnet-4", true),
        ("mistralai/mistral-medium-3", true),
        ("meta-llama/llama-guard-4-12b", false),
        ("qwen/qwen3-30b-a3b", true),
        ("qwen/qwen3-8b", true),
        ("qwen/qwen3-14b", true),
        ("qwen/qwen3-32b", true),
        ("qwen/qwen3-235b-a22b", true),
        ("openai/o4-mini-high", true),
        ("openai/o3", true),
        ("openai/o3:batch", true),
        ("openai/o4-mini", true),
        ("openai/o4-mini:batch", true),
        ("openai/gpt-4.1", true),
        ("openai/gpt-4.1:batch", true),
        ("openai/gpt-4.1-mini", true),
        ("openai/gpt-4.1-mini:batch", true),
        ("openai/gpt-4.1-nano", true),
        ("openai/gpt-4.1-nano:batch", true),
        ("meta-llama/llama-4-maverick", true),
        ("meta-llama/llama-4-scout", true),
        ("deepseek/deepseek-chat-v3-0324", true),
        ("openai/o1-pro", false),
        ("mistralai/mistral-small-3.1-24b-instruct", true),
        ("google/gemma-3-4b-it", false),
        ("google/gemma-3-12b-it", true),
        ("cohere/command-a", false),
        ("rekaai/reka-flash-3", false),
        ("google/gemma-3-27b-it", true),
        ("thedrummer/skyfall-36b-v2", false),
        ("perplexity/sonar-reasoning-pro", false),
        ("perplexity/sonar-pro", false),
        ("perplexity/sonar-deep-research", false),
        ("mistralai/mistral-saba", true),
        ("openai/o3-mini-high", true),
        ("aion-labs/aion-rp-llama-3.1-8b", false),
        ("qwen/qwen2.5-vl-72b-instruct", false),
        ("qwen/qwen-plus", true),
        ("openai/o3-mini", true),
        ("openai/o3-mini:batch", true),
        ("mistralai/mistral-small-24b-instruct-2501", false),
        ("perplexity/sonar", false),
        ("deepseek/deepseek-r1", true),
        ("minimax/minimax-01", false),
        ("microsoft/phi-4", false),
        ("deepseek/deepseek-chat", true),
        ("sao10k/l3.3-euryale-70b", false),
        ("openai/o1", true),
        ("cohere/command-r7b-12-2024", false),
        ("meta-llama/llama-3.3-70b-instruct", true),
        ("amazon/nova-lite-v1", true),
        ("amazon/nova-micro-v1", true),
        ("amazon/nova-pro-v1", true),
        ("openai/gpt-4o-2024-11-20", true),
        ("mistralai/mistral-large-2407", true),
        ("qwen/qwen-2.5-coder-32b-instruct", false),
        ("thedrummer/unslopnemo-12b", false),
        ("anthracite-org/magnum-v4-72b", false),
        ("qwen/qwen-2.5-7b-instruct", true),
        ("meta-llama/llama-3.2-1b-instruct", false),
        ("meta-llama/llama-3.2-3b-instruct", false),
        ("qwen/qwen-2.5-72b-instruct", true),
        ("cohere/command-r-08-2024", true),
        ("cohere/command-r-plus-08-2024", true),
        ("sao10k/l3.1-euryale-70b", true),
        ("nousresearch/hermes-3-llama-3.1-70b", false),
        ("nousresearch/hermes-3-llama-3.1-405b", false),
        ("sao10k/l3-lunaris-8b", false),
        ("openai/gpt-4o-2024-08-06", true),
        ("meta-llama/llama-3.1-70b-instruct", true),
        ("meta-llama/llama-3.1-8b-instruct", true),
        ("mistralai/mistral-nemo", true),
        ("openai/gpt-4o-mini", true),
        ("openai/gpt-4o-mini-2024-07-18", true),
        ("openai/gpt-4o-mini:batch", true),
        ("google/gemma-2-27b-it", false),
        ("openai/gpt-4o", true),
        ("openai/gpt-4o-2024-05-13", true),
        ("openai/gpt-4o:batch", true),
        ("mistralai/mixtral-8x22b-instruct", true),
        ("microsoft/wizardlm-2-8x22b", false),
        ("openai/gpt-4-turbo", true),
        ("openai/gpt-4-turbo:batch", true),
        ("mistralai/mistral-large", true),
        ("openai/gpt-3.5-turbo-0613", true),
        ("openrouter/auto", true),
        ("openai/gpt-3.5-turbo-instruct", false),
        ("openai/gpt-3.5-turbo-16k", true),
        ("mancer/weaver", false),
        ("undi95/remm-slerp-l2-13b", false),
        ("gryphe/mythomax-l2-13b", false),
        ("openai/gpt-3.5-turbo", true),
        ("openai/gpt-3.5-turbo:batch", true),
        ("openai/gpt-4", true),
    ]
}
